kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  -  name:
     protocol: TCP
     port: 80 #service port
     targetPort: 80 # container port